// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: protos/game.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GamerClient is the client API for Gamer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GamerClient interface {
	GetGameDetail(ctx context.Context, in *GameRequest, opts ...grpc.CallOption) (*GameResponse, error)
}

type gamerClient struct {
	cc grpc.ClientConnInterface
}

func NewGamerClient(cc grpc.ClientConnInterface) GamerClient {
	return &gamerClient{cc}
}

func (c *gamerClient) GetGameDetail(ctx context.Context, in *GameRequest, opts ...grpc.CallOption) (*GameResponse, error) {
	out := new(GameResponse)
	err := c.cc.Invoke(ctx, "/pb.Gamer/GetGameDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GamerServer is the server API for Gamer service.
// All implementations must embed UnimplementedGamerServer
// for forward compatibility
type GamerServer interface {
	GetGameDetail(context.Context, *GameRequest) (*GameResponse, error)
	mustEmbedUnimplementedGamerServer()
}

// UnimplementedGamerServer must be embedded to have forward compatible implementations.
type UnimplementedGamerServer struct {
}

func (UnimplementedGamerServer) GetGameDetail(context.Context, *GameRequest) (*GameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGameDetail not implemented")
}
func (UnimplementedGamerServer) mustEmbedUnimplementedGamerServer() {}

// UnsafeGamerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GamerServer will
// result in compilation errors.
type UnsafeGamerServer interface {
	mustEmbedUnimplementedGamerServer()
}

func RegisterGamerServer(s grpc.ServiceRegistrar, srv GamerServer) {
	s.RegisterService(&Gamer_ServiceDesc, srv)
}

func _Gamer_GetGameDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamerServer).GetGameDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Gamer/GetGameDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamerServer).GetGameDetail(ctx, req.(*GameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Gamer_ServiceDesc is the grpc.ServiceDesc for Gamer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Gamer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Gamer",
	HandlerType: (*GamerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGameDetail",
			Handler:    _Gamer_GetGameDetail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/game.proto",
}
